"""
Kernell OS SDK — Formal Intent Firewall (The Kernel)
════════════════════════════════════════════════════════
A strict, capability-based, deterministic Mandatory Access Control (MAC) 
system. This replaces the legacy semantic firewall.

Features:
- Strict Canonicalization (Base64/Hex/Unicode decoding)
- Capability-Based Security (No semantic matching, only cryptographic capabilities)
- Trajectory Validation (State-machine invariant checking)
- Taint Tracking (Untrusted LLM data vs System data)
"""
from __future__ import annotations

import base64
import json
import logging
import re
import urllib.parse
import uuid
import time
from dataclasses import dataclass, field
from enum import Enum
from typing import Callable, Dict, List, Optional, Any, Set

logger = logging.getLogger("kernell.cognitive.firewall")

class ActionType(str, Enum):
    # Core system
    READ_FILE = "read_file"
    WRITE_FILE = "write_file"
    DELETE_FILE = "delete_file"
    LIST_DIR = "list_dir"
    EXECUTE_COMMAND = "execute_command"
    NETWORK_REQUEST = "network_request"
    RUN_TESTS = "run_tests"
    GIT_OPERATION = "git_operation"
    INSTALL_PACKAGE = "install_package"
    SYSTEM_CALL = "system_call"
    
    # Economic / Ledger
    TRANSFER = "transfer"
    CREATE_WALLET = "create_wallet"
    ESCROW_RELEASE = "escrow_release"
    SETTLE_EXTERNAL = "settle_external"

class RiskLevel(str, Enum):
    NONE = "none"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"

class FirewallVerdict(str, Enum):
    APPROVED = "approved"
    DENIED = "denied"
    PENDING = "pending"

class TaintLevel(str, Enum):
    CLEAN = "clean"       # Generated by deterministic system code
    TAINTED = "tainted"   # Generated by LLM / External input

@dataclass
class Capability:
    """A formal permission slip."""
    action: ActionType
    constraints: Dict[str, Any]
    granted_to: str
    is_revoked: bool = False

@dataclass
class AgentIntent:
    intent_id: str = field(default_factory=lambda: f"intent-{uuid.uuid4().hex[:10]}")
    agent_id: str = ""
    action_type: ActionType = ActionType.READ_FILE
    target: str = ""              
    payload: str = ""             
    context: str = ""             
    timestamp: float = field(default_factory=time.time)
    
    # --- New V2 Properties ---
    structured_payload: Dict[str, Any] = field(default_factory=dict)
    capability_token: str = ""    # Must map to a valid Capability
    taint_level: TaintLevel = TaintLevel.TAINTED

@dataclass
class FirewallDecision:
    intent_id: str
    agent_id: str
    action_type: str
    target: str
    risk: RiskLevel
    verdict: FirewallVerdict
    reason: str
    timestamp: float = field(default_factory=time.time)

    def to_event(self) -> dict:
        return {
            "intent_id": self.intent_id,
            "agent": self.agent_id,
            "action": self.action_type,
            "target": self.target[:200],
            "risk": self.risk.value,
            "verdict": self.verdict.value,
            "reason": self.reason,
        }

class SecurityViolation(Exception):
    pass

class PayloadCanonicalizer:
    """Ensures payloads cannot hide malicious intent via encoding."""
    
    @classmethod
    def canonicalize(cls, payload: Any, depth: int = 0) -> Any:
        if depth > 10:
            raise SecurityViolation("Payload too deeply nested (Billion Laughs / Decompression bomb prevention).")
        
        if isinstance(payload, str):
            return cls._decode_string(payload)
        elif isinstance(payload, dict):
            return {k: cls.canonicalize(v, depth + 1) for k, v in sorted(payload.items())}
        elif isinstance(payload, list):
            return [cls.canonicalize(item, depth + 1) for item in payload]
        return payload

    @classmethod
    def _decode_string(cls, text: str) -> str:
        # 1. URL Decode
        text = urllib.parse.unquote(text)
        # 2. Try Base64 Decode
        try:
            if re.match(r'^[A-Za-z0-9+/]+={0,2}$', text) and len(text) % 4 == 0:
                decoded = base64.b64decode(text).decode('utf-8')
                if all(ord(c) < 128 for c in decoded):
                    text = decoded
        except Exception as e:
            import logging
            logging.warning(f'Suppressed error in {__name__}: {e}')
        # 3. Unicode normalization
        import unicodedata
        text = unicodedata.normalize('NFKC', text)
        return text.strip()


class InvariantEngine:
    """Global system laws that cannot be broken under any circumstance."""
    
    @staticmethod
    def check_transfer(payload: Dict[str, Any], state: Dict[str, Any]) -> None:
        source = str(payload.get("from", "")).lower()
        target = str(payload.get("to", "")).lower()
        amount = float(payload.get("amount", 0))
        
        if "escrow" in source and "external" in target:
            raise SecurityViolation("INVARIANT BROKEN: Escrow funds cannot flow directly to external wallets.")
            
        if amount > state.get("max_transaction_limit", 1000):
            raise SecurityViolation(f"INVARIANT BROKEN: Transaction amount {amount} exceeds limit.")

class IntentFirewall:
    """
    Formal Intent Firewall (MAC).
    Replaces LLM semantic checks with strict cryptographic constraints and canonicalization.
    """
    def __init__(
        self,
        auto_approve: Optional[Set[ActionType]] = None,
        manual_approve: Optional[Set[ActionType]] = None,
        always_deny_patterns: Optional[List[re.Pattern]] = None,
        on_decision: Optional[Callable] = None,
    ):
        self._on_decision = on_decision
        self._capabilities: Dict[str, Capability] = {}
        self._system_state: Dict[str, Any] = {"max_transaction_limit": 500}
        self._pending: Dict[str, AgentIntent] = {}
        self._decision_log: List[FirewallDecision] = []

    def grant_capability(self, token: str, cap: Capability):
        """Usually called by the orchestrator/kernel, not the LLM."""
        self._capabilities[token] = cap

    def evaluate(self, intent: AgentIntent) -> FirewallDecision:
        """
        Evaluate using formal rules:
        1. Canonicalize
        2. Check Capability Auth
        3. Check Constraints
        4. Check Invariants
        """
        try:
            # 1. Canonicalization
            clean_payload = PayloadCanonicalizer.canonicalize(intent.structured_payload or {"raw": intent.payload})
            
            # 2. Authorization (Capability check)
            # For backward compatibility on non-economic tasks, if capability is missing we deny unless it's basic READ.
            if intent.action_type not in [ActionType.READ_FILE, ActionType.LIST_DIR]:
                if intent.capability_token not in self._capabilities:
                    raise SecurityViolation("Missing or invalid capability token. ALL execution requires capabilities.")
                
                cap = self._capabilities[intent.capability_token]
                if cap.is_revoked or cap.action != intent.action_type or cap.granted_to != intent.agent_id:
                    raise SecurityViolation("Capability mismatch (action, agent, or revoked).")

                # 3. Constraint checking
                for k, required_val in cap.constraints.items():
                    val = clean_payload.get(k)
                    if isinstance(required_val, list) and val not in required_val:
                        raise SecurityViolation(f"Constraint failed: {k}={val} not in {required_val}")
                    elif not isinstance(required_val, list) and val != required_val:
                        raise SecurityViolation(f"Constraint failed: {k}={val} != {required_val}")

            # 4. Global Invariants
            if intent.action_type == ActionType.TRANSFER:
                InvariantEngine.check_transfer(clean_payload, self._system_state)
            
            # 5. Taint tracking on high-risk operations
            if intent.action_type in [ActionType.EXECUTE_COMMAND, ActionType.SETTLE_EXTERNAL, ActionType.SYSTEM_CALL]:
                if intent.taint_level == TaintLevel.TAINTED:
                    raise SecurityViolation("High-risk operations cannot accept TAINTED input directly from LLM.")

            decision = FirewallDecision(
                intent_id=intent.intent_id,
                agent_id=intent.agent_id,
                action_type=intent.action_type.value,
                target=intent.target,
                risk=RiskLevel.LOW,
                verdict=FirewallVerdict.APPROVED,
                reason="Passed formal capability and invariant checks."
            )
            self._record(decision)
            return decision

        except SecurityViolation as e:
            decision = FirewallDecision(
                intent_id=intent.intent_id,
                agent_id=intent.agent_id,
                action_type=intent.action_type.value,
                target=intent.target,
                risk=RiskLevel.CRITICAL,
                verdict=FirewallVerdict.DENIED,
                reason=str(e)
            )
            self._record(decision)
            return decision
            
    def _record(self, decision: FirewallDecision) -> None:
        self._decision_log.append(decision)
        if self._on_decision:
            self._on_decision(decision.to_event())
        logger.warning(
            f"Firewall: {decision.verdict.value} | "
            f"{decision.agent_id} -> {decision.action_type} "
            f"({decision.target[:60]}) | Reason: {decision.reason}"
        )
