#!/usr/bin/env python3
"""
Security release gates based on measured coverage and invariant evidence.

Expected inputs:
- coverage JSON generated by: pytest --cov=kernell_sdk --cov-report=json:coverage.json
"""

from __future__ import annotations

import json
import pathlib
import re
import sys
from typing import Dict, List


ROOT = pathlib.Path(__file__).resolve().parents[1]
COVERAGE_JSON = ROOT / "coverage.json"
TESTS_DIR = ROOT / "tests" / "security"

# Invariant -> code files whose coverage approximates this invariant
INVARIANT_FILES: Dict[str, List[str]] = {
    "E1": ["kernell_sdk/runtime/firecracker/auth_protocol.py"],
    "E2": ["kernell_sdk/runtime/firecracker/auth_protocol.py"],
    "E3": ["kernell_sdk/runtime/firecracker/auth_protocol.py"],
    "E4": ["kernell_sdk/runtime/firecracker/auth_protocol.py"],
    "E5": ["kernell_sdk/runtime/firecracker_runtime.py"],
    "E6": ["kernell_sdk/runtime/firecracker_runtime.py"],
    "E7": ["kernell_sdk/runtime/firecracker/auth_protocol.py"],
    "L1": ["kernell_sdk/runtime/firecracker/ledger.py"],
    "L2": ["kernell_sdk/runtime/firecracker/ledger.py"],
    "L3": ["kernell_sdk/runtime/firecracker/ledger.py"],
    "L4": ["kernell_sdk/runtime/firecracker/ledger.py", "kernell_sdk/escrow/manager.py"],
    "L5": ["kernell_sdk/runtime/firecracker/ledger.py"],
    "S1": ["kernell_sdk/escrow/manager.py"],
    "S2": ["kernell_sdk/escrow/manager.py"],
    "S3": ["kernell_sdk/escrow/manager.py"],
    "S4": ["kernell_sdk/escrow/manager.py"],
    "S5": ["kernell_sdk/escrow/manager.py"],
    "S6": ["kernell_sdk/escrow/manager.py"],
    "T1": ["kernell_sdk/runtime/firecracker/server.py"],
    "T2": ["kernell_sdk/runtime/firecracker_runtime.py", "kernell_sdk/escrow/manager.py"],
    "T3": [
        "kernell_sdk/runtime/firecracker/auth_protocol.py",
        "kernell_sdk/runtime/firecracker_runtime.py",
        "kernell_sdk/escrow/manager.py",
    ],
}

CRITICAL_PREFIXES = ("E", "S")
CRITICAL_SINGLE = {"L3"}
MIN_GENERAL = 80.0
MIN_CRITICAL = 95.0
MIN_BRANCH_GENERAL = 70.0
MIN_BRANCH_CRITICAL = 90.0
REQUIRED_INVARIANTS = tuple(INVARIANT_FILES.keys())


def load_coverage() -> dict:
    if not COVERAGE_JSON.exists():
        raise SystemExit(f"[FAIL] coverage file missing: {COVERAGE_JSON}")
    data = json.loads(COVERAGE_JSON.read_text())
    if not data or "files" not in data or not data["files"]:
        raise SystemExit("[FAIL] invalid coverage report: missing/empty 'files'")
    totals = data.get("totals", {})
    if "num_branches" not in totals:
        raise SystemExit("[FAIL] branch coverage data missing. Run pytest with --cov-branch.")
    return data


def file_percent(cov: dict, relpath: str) -> float:
    for key, entry in cov.get("files", {}).items():
        if key.endswith(relpath):
            summary = entry.get("summary", {})
            return float(summary.get("percent_covered", 0.0))
    return 0.0


def file_branch_percent(cov: dict, relpath: str) -> float:
    for key, entry in cov.get("files", {}).items():
        if key.endswith(relpath):
            summary = entry.get("summary", {})
            total = int(summary.get("num_branches", 0))
            covered = int(summary.get("covered_branches", 0))
            if total == 0:
                return 100.0
            return (covered / total) * 100.0
    return 0.0


def collect_invariant_tags() -> set[str]:
    found: set[str] = set()
    pattern = re.compile(r'@pytest\.mark\.invariant\("([A-Z]\d+)"\)')
    for path in TESTS_DIR.glob("test_*.py"):
        for m in pattern.finditer(path.read_text()):
            found.add(m.group(1))
    return found


def files_without_invariant_marker() -> list[str]:
    missing: list[str] = []
    pattern = re.compile(r'@pytest\.mark\.invariant\("([A-Z]\d+)"\)')
    for path in TESTS_DIR.glob("test_*.py"):
        src = path.read_text()
        if not pattern.search(src):
            missing.append(str(path.relative_to(ROOT)))
    return sorted(missing)


def threshold_for(inv: str) -> float:
    if inv in CRITICAL_SINGLE or inv.startswith(CRITICAL_PREFIXES):
        return MIN_CRITICAL
    return MIN_GENERAL


def branch_threshold_for(inv: str) -> float:
    if inv in CRITICAL_SINGLE or inv.startswith(CRITICAL_PREFIXES):
        return MIN_BRANCH_CRITICAL
    return MIN_BRANCH_GENERAL


def main() -> int:
    cov = load_coverage()
    tags = collect_invariant_tags()

    failures: list[str] = []
    untagged_files = files_without_invariant_marker()
    if untagged_files:
        failures.append(
            "security test files missing invariant marker coverage: " + ", ".join(untagged_files)
        )

    missing_required = [inv for inv in REQUIRED_INVARIANTS if inv not in tags]
    if missing_required:
        failures.append("missing required invariant markers: " + ", ".join(missing_required))

    unknown_markers = sorted(tags - set(REQUIRED_INVARIANTS))
    if unknown_markers:
        failures.append("unknown invariant markers found: " + ", ".join(unknown_markers))

    for inv, files in INVARIANT_FILES.items():
        # enforce explicit test tag presence for each invariant
        if inv not in tags:
            continue
        line_scores = [file_percent(cov, f) for f in files]
        branch_scores = [file_branch_percent(cov, f) for f in files]
        line_score = min(line_scores) if line_scores else 0.0
        branch_score = min(branch_scores) if branch_scores else 0.0
        line_threshold = threshold_for(inv)
        branch_threshold = branch_threshold_for(inv)
        if line_score < line_threshold:
            failures.append(
                f"{inv}: line coverage {line_score:.2f}% < required {line_threshold:.2f}%"
            )
        if branch_score < branch_threshold:
            failures.append(
                f"{inv}: branch coverage {branch_score:.2f}% < required {branch_threshold:.2f}%"
            )

    if failures:
        print("[FAIL] Security gates failed:")
        for item in failures:
            print(f" - {item}")
        return 1

    print("[PASS] Security gates satisfied.")
    return 0


if __name__ == "__main__":
    sys.exit(main())

