import hashlib
import json
from enum import Enum
from typing import Dict, List, Optional, Any
from pydantic import BaseModel, Field, model_validator

class ActionType(str, Enum):
    READ_FILE = "read_file"
    WRITE_FILE = "write_file"
    LIST_DIR = "list_dir"
    TRANSFORM = "transform"
    EXECUTE_CODE = "execute_code"
    NETWORK_REQUEST = "network_request"
    VALIDATE = "validate"
    NOOP = "noop"

class DataSensitivity(str, Enum):
    PUBLIC = "public"
    INTERNAL = "internal"
    SECRET = "secret"
    
    @property
    def level(self) -> int:
        return {"public": 0, "internal": 1, "secret": 2}[self.value]

class DataSourceType(str, Enum):
    FILE = "file"
    NETWORK = "network"
    MEMORY = "memory"
    USER_INPUT = "user_input"

class DataSinkType(str, Enum):
    FILE = "file"
    NETWORK = "network"
    MEMORY = "memory"
    NONE = "none"

class DataRef(BaseModel):
    """
    Reference to a data node within the plan.
    Strict declarative metadata, no actual payload.
    """
    id: str = Field(..., description="Unique ID of the data node")
    sensitivity: DataSensitivity = DataSensitivity.PUBLIC
    source: DataSourceType

class PlanStep(BaseModel):
    id: str
    action: ActionType
    inputs: List[str] = Field(default_factory=list)
    outputs: List[str] = Field(default_factory=list)
    params: Dict[str, str] = Field(default_factory=dict)
    
    source_type: Optional[DataSourceType] = None
    sink_type: Optional[DataSinkType] = None

class PlanIR(BaseModel):
    """
    Plan Intermediate Representation.
    The strict JSON output generated by the LLM planner.
    """
    plan_id: str
    goal: str
    data_nodes: List[DataRef]
    steps: List[PlanStep]
    declared_intent: str
    risk_hint: Optional[str] = None

    def get_step(self, step_id: str) -> PlanStep:
        for s in self.steps:
            if s.id == step_id:
                return s
        raise ValueError(f"Step {step_id} not found")

    def get_data(self, data_id: str) -> DataRef:
        for d in self.data_nodes:
            if d.id == data_id:
                return d
        raise ValueError(f"Data node {data_id} not found")
        
    def hash_plan(self) -> str:
        """
        Creates a deterministic, canonical SHA-256 hash of the entire plan.
        Ignores order of dict keys but evaluates structure strictly.
        """
        # Convert to model dump (which handles Enums natively)
        raw_dict = self.model_dump()
        
        # We drop the 'risk_hint' from the hash to allow minor variations in LLM explanations 
        # without breaking the core logic hash, though normally everything should be hashed.
        # For maximum strictness, we hash EVERYTHING.
        
        # Serialize to canonical JSON (sorted keys, no spaces)
        canonical_json = json.dumps(raw_dict, sort_keys=True, separators=(',', ':'))
        
        return hashlib.sha256(canonical_json.encode('utf-8')).hexdigest()

class PlanValidator:
    """
    Stateless semantic analysis engine.
    Finds invalid data flows BEFORE execution using iterative taint propagation.
    """
    def __init__(self, plan: PlanIR):
        self.plan = plan

    def validate(self) -> Dict[str, Any]:
        """Runs the semantic data flow validation rules."""
        violations = []
        
        # 0. Graph Completeness Enforcement & "Closed World Assumption"
        declared_nodes = {node.id: node for node in self.plan.data_nodes}
        
        for step in self.plan.steps:
            # Enforce all inputs and outputs must be declared
            for io_node in step.inputs + step.outputs:
                if io_node not in declared_nodes:
                    violations.append({
                        "rule": "UNDECLARED_NODE",
                        "step_id": step.id,
                        "node_id": io_node,
                        "reason": f"Node {io_node} used in step {step.id} but not declared in data_nodes."
                    })
                    
            # Block data creation out of thin air
            if not step.inputs and step.action not in [ActionType.READ_FILE]:
                violations.append({
                    "rule": "SOURCE_FORGERY",
                    "step_id": step.id,
                    "reason": f"Step {step.id} ({step.action}) has no inputs but is not a valid source action."
                })
                
        if violations:
            return {"valid": False, "violations": violations} # Fail early on integrity
            
        # 1. Initialize Effective Sensitivities (Source Classification, NOT LLM Trust)
        effective_levels = {}
        for node in self.plan.data_nodes:
            # Trust Bootstrap Poisoning Fix: Override sensitivity by Source
            base_level = node.sensitivity.level
            if node.source == DataSourceType.FILE:
                # Assuming all files are at least internal until we have granular path policies
                base_level = max(base_level, DataSensitivity.INTERNAL.level)
            
            effective_levels[node.id] = base_level
            
        # 2. Iterative Taint Propagation (handles DAGs, Branching, and Implicit Flows)
        # O(V+E) instead of DFS path explosion.
        changed = True
        iterations = 0
        MAX_ITERATIONS = 1000 # Graph Explosion Guard
        
        while changed and iterations < MAX_ITERATIONS:
            changed = False
            iterations += 1
            for step in self.plan.steps:
                # Find max sensitivity of all inputs
                max_in = 0
                for inp in step.inputs:
                    max_in = max(max_in, effective_levels.get(inp, 0))
                
                # Propagate to ALL outputs (Implicit Flow & Transform semantics)
                for out in step.outputs:
                    if out in effective_levels and effective_levels[out] < max_in:
                        effective_levels[out] = max_in
                        changed = True
                        
        if iterations >= MAX_ITERATIONS:
            violations.append({"rule": "GRAPH_EXPLOSION", "reason": "Plan complexity exceeded max iterations or cyclic graph detected."})
            return {"valid": False, "violations": violations}
            
        # 3. Edge / Sink Validation
        for step in self.plan.steps:
            # Rule: Arbitrary Code Execution Block
            if step.action == ActionType.EXECUTE_CODE:
                violations.append({
                    "rule": "UNTRUSTED_EXECUTION",
                    "step_id": step.id,
                    "reason": "Arbitrary code execution (EXECUTE_CODE) is categorically blocked by the Intent Firewall."
                })
                continue
                
            # Compute effective sensitivity entering this step
            step_sensitivity = 0
            for inp in step.inputs:
                step_sensitivity = max(step_sensitivity, effective_levels.get(inp, 0))
                
            # Rule: Data Exfiltration via Network
            if step.sink_type == DataSinkType.NETWORK or step.action == ActionType.NETWORK_REQUEST:
                if step_sensitivity >= DataSensitivity.INTERNAL.level:
                    violations.append({
                        "rule": "DATA_EXFILTRATION",
                        "step_id": step.id,
                        "sensitivity_level": step_sensitivity,
                        "reason": f"Sensitive data (level {step_sensitivity}) flows into a network sink via step {step.id}."
                    })

        return {
            "valid": len(violations) == 0,
            "violations": violations
        }

import uuid
import time
import base64
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric import ed25519

class CapabilityToken(BaseModel):
    """
    Cryptographic binding that grants execution authority.
    Must be signed by the Validator and verified by Orchestrator.
    """
    token_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    plan_hash: str
    policy_version: str
    issued_at: float
    expires_at: float
    execution_id: str
    signature: Optional[str] = None
    
    def canonical_payload(self) -> bytes:
        payload = f"{self.token_id}:{self.plan_hash}:{self.policy_version}:{self.issued_at}:{self.expires_at}:{self.execution_id}"
        return payload.encode('utf-8')

class TokenAuthority:
    """Signs and verifies capability tokens."""
    def __init__(self, private_key: ed25519.Ed25519PrivateKey):
        self.private_key = private_key
        self.public_key = private_key.public_key()
        
    def sign_token(self, token: CapabilityToken) -> CapabilityToken:
        signature = self.private_key.sign(token.canonical_payload())
        token.signature = base64.b64encode(signature).decode('utf-8')
        return token
        
    def verify_token(self, token: CapabilityToken) -> bool:
        if not token.signature:
            return False
            
        if time.time() > token.expires_at:
            return False
            
        try:
            sig_bytes = base64.b64decode(token.signature)
            self.public_key.verify(sig_bytes, token.canonical_payload())
            return True
        except Exception:
            return False

class PlanDriftError(Exception):
    pass

class InvalidCapabilityToken(Exception):
    pass

class UnsupportedActionError(Exception):
    pass

class OrchestratorStub:
    """
    Deterministic AST interpreter with Stateful Provenance Enforcement.
    Executes validated plans. Fails closed on any deviation or runtime taint violation.
    """
    def __init__(self, authority: TokenAuthority, provenance_store=None):
        self.authority = authority
        self.store = provenance_store  # Duck-typed KV store (Redis or Dict)
        self.ACTION_MAP = {
            ActionType.READ_FILE: self._read_file,
            ActionType.TRANSFORM: self._transform,
            ActionType.WRITE_FILE: self._write_file,
            ActionType.NETWORK_REQUEST: self._network_request,
            ActionType.LIST_DIR: self._list_dir,
            ActionType.NOOP: self._noop,
            # EXECUTE_CODE and VALIDATE are blocked or handled elsewhere
        }
    
    def execute(self, plan: PlanIR, token: CapabilityToken) -> Dict[str, Any]:
        # Step 1: Mandatory Re-hash (Drift Prevention)
        computed_hash = plan.hash_plan()
        if computed_hash != token.plan_hash:
            raise PlanDriftError("Plan hash mismatch. Plan was mutated after signing.")
            
        # Step 2: Cryptographic Verification (Parent Only)
        # If authority is None, we are inside the untrusted worker and assume Parent already verified.
        if self.authority is not None:
            if not self.authority.verify_token(token):
                raise InvalidCapabilityToken("Token signature is invalid.")
            
        # Step 3: Explicit Expiration Check (Defense in depth)
        if time.time() > token.expires_at:
            raise InvalidCapabilityToken("Token has expired.")
            
        # Step 4: Strict Interpreter (No Shell, No Eval) with Dynamic Taint Tracking
        # runtime_values stores tuples: (value, dynamic_sensitivity)
        runtime_values = {}
        execution_log = []
        
        for step in plan.steps:
            handler = self.ACTION_MAP.get(step.action)
            if not handler:
                raise UnsupportedActionError(f"Action {step.action} is not supported by strict interpreter.")
                
            # Execute AST node. Handler returns (result_value, result_sensitivity)
            res_val, res_sens = handler(step, runtime_values)
            
            # Map outputs to runtime values
            if res_val is not None and step.outputs:
                for out_node in step.outputs:
                    runtime_values[out_node] = (res_val, res_sens)
                    
            execution_log.append(f"Executed {step.action} -> sensitivity: {res_sens}")
            
        return {
            "status": "success",
            "log": execution_log,
            "runtime_state": runtime_values
        }

    def _resolve_inode(self, path: str) -> str:
        import os
        try:
            st = os.stat(path)
            return f"{st.st_dev}:{st.st_ino}"
        except FileNotFoundError:
            # For new files, we return a virtual path identifier until created.
            # In a real system, the file is created first, then stat'd.
            return f"virtual:{path}"

    def _read_file(self, step: PlanStep, state: Dict[str, Any]) -> tuple:
        path = step.params.get("path", "/dev/null")
        inode = self._resolve_inode(path)
        
        # Base sensitivity is INTERNAL for any filesystem read
        base_level = DataSensitivity.INTERNAL.level
        
        persisted_level = 0
        if self.store is not None:
            persisted_level = self.store.get(inode) or 0
            
        effective_level = max(base_level, persisted_level)
        
        # Return mock value and its dynamic sensitivity
        return f"file_content({inode})", effective_level
        
    def _transform(self, step: PlanStep, state: Dict[str, Any]) -> tuple:
        # Dynamic Taint Propagation: output gets max of inputs
        max_in_sens = 0
        inputs_data = []
        for inp in step.inputs:
            val, sens = state.get(inp, ("empty", 0))
            inputs_data.append(val)
            max_in_sens = max(max_in_sens, sens)
            
        return f"transformed({','.join(inputs_data)})", max_in_sens
        
    def _write_file(self, step: PlanStep, state: Dict[str, Any]) -> tuple:
        path = step.params.get("path", "/dev/null")
        
        # Calculate sensitivity of data being written
        max_in_sens = 0
        for inp in step.inputs:
            _, sens = state.get(inp, (None, 0))
            max_in_sens = max(max_in_sens, sens)
            
        # In a real system, create file if not exists here to get inode
        inode = self._resolve_inode(path)
        
        if self.store is not None:
            existing_level = self.store.get(inode) or 0
            new_level = max(existing_level, max_in_sens)
            self.store.set(inode, new_level)
            
        return "mock_write_success", max_in_sens
        
    def _network_request(self, step: PlanStep, state: Dict[str, Any]) -> tuple:
        # Runtime Egress Firewall
        max_in_sens = 0
        for inp in step.inputs:
            _, sens = state.get(inp, (None, 0))
            max_in_sens = max(max_in_sens, sens)
            
        if max_in_sens >= DataSensitivity.INTERNAL.level:
            raise Exception("RUNTIME EXFILTRATION BLOCKED: Attempted to send sensitive data over network.")
            
        return "mock_network_success", max_in_sens
        
    def _list_dir(self, step: PlanStep, state: Dict[str, Any]) -> tuple:
        # Base sensitivity for reading directory metadata
        return "mock_dir_list", DataSensitivity.INTERNAL.level
        
    def _noop(self, step: PlanStep, state: Dict[str, Any]) -> tuple:
        return "noop", 0

